-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 11:52:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema template
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `op_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `op_user` ;

CREATE TABLE IF NOT EXISTS `op_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(32) NOT NULL COMMENT '',
  `passwd` VARCHAR(45) NOT NULL COMMENT '',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '运营用户表';

CREATE UNIQUE INDEX `name_UNIQUE` ON `op_user` (`name` ASC)  COMMENT '';

-- -----------------------------------------------------
-- Table `param`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `param`;

CREATE TABLE IF NOT EXISTS `param` (
  `name` VARCHAR(64) NOT NULL COMMENT '',
  `value` VARCHAR(128) NULL COMMENT '',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '参数及常量表';



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
