-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 11:52:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema template
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `op_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `op_user` ;

CREATE TABLE IF NOT EXISTS `op_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(32) NOT NULL COMMENT '',
  `passwd` VARCHAR(45) NOT NULL COMMENT '',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '运营用户表';

CREATE UNIQUE INDEX `name_UNIQUE` ON `op_user` (`name` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `param`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `param`;

CREATE TABLE IF NOT EXISTS `param` (
  `name` VARCHAR(64) NOT NULL COMMENT '',
  `value` VARCHAR(128) NULL COMMENT '',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`name`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '参数及常量表';


-- -----------------------------------------------------
-- Table `sms_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms_template` ;

CREATE TABLE IF NOT EXISTS `sms_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `template_id` BIGINT(20) NOT NULL COMMENT '模板id',
  `content` VARCHAR(512) NOT NULL COMMENT '模板内容',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '短信模板表';

CREATE UNIQUE INDEX `template_id_UNIQUE` ON `sms_template` (`template_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `push_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `push_template` ;

CREATE TABLE IF NOT EXISTS `push_template` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
    `template_id` BIGINT(20) NOT NULL COMMENT '模板id',
    `content` VARCHAR(512) NOT NULL COMMENT '模板内容',
    `create_time` DATETIME NOT NULL COMMENT '',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
    PRIMARY KEY (`id`)  COMMENT '')
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COMMENT = 'push模板表';

CREATE UNIQUE INDEX `template_id_UNIQUE` ON `push_template` (`template_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `email_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email_template` ;

CREATE TABLE IF NOT EXISTS `email_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `template_id` BIGINT(20) NOT NULL COMMENT '模板id',
  `subject` VARCHAR(256) NOT NULL COMMENT '',
  `content` VARCHAR(2048) NOT NULL COMMENT '模板内容',
  `receiver` VARCHAR(256) NULL COMMENT '',
  `create_time` DATETIME NOT NULL COMMENT '',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '邮件模板表';

CREATE UNIQUE INDEX `template_id_UNIQUE` ON `email_template` (`template_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `timer_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timer_task` ;

CREATE TABLE IF NOT EXISTS `timer_task` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
    `type` INT(11) NOT NULL COMMENT '任务类型：1、发定时短信；2、发定时push',
    `param` VARCHAR(512) NULL COMMENT '参数',
    `process_time` DATETIME NOT NULL COMMENT '处理时间',
    `processor` VARCHAR(64) NULL COMMENT '处理的机器',
    `create_time` DATETIME NOT NULL COMMENT '',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
    PRIMARY KEY (`id`)  COMMENT '')
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COMMENT = '定时任务表';

CREATE INDEX `index2` ON `timer_task` (`processor` ASC, `process_time` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `wx_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wx_user` ;

CREATE TABLE IF NOT EXISTS `wx_user` (
    `open_id` VARCHAR(128) NOT NULL COMMENT '',
    `user_id` BIGINT(20) NULL COMMENT '',
    `user_info` VARCHAR(2048) NULL COMMENT '',
    `create_time` DATETIME NOT NULL COMMENT '',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
    PRIMARY KEY (`open_id`)  COMMENT '')
    ENGINE = InnoDB;

CREATE INDEX `index2` ON `wx_user` (`user_id` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
